--- #YAML:1.0
name:               CGI-Session-Driver-redis
version:            0.4
abstract:           Persistent session data in CGI applications
author:
    - Steve Kemp <steve@steve.org.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI::Session:  4
    Redis:         ~
    Test::More:    ~
resources:
    bugtracker:  https://github.com/skx/CGI--Session--Driver--redis/issues
    homepage:    https://github.com/skx/CGI--Session--Driver--redis/
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/skx/CGI--Session--Driver--redis.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
